export { default as Hero } from './Hero'
export { default as Benefits } from './Benefits'
export { default as Deliverables } from './Deliverables'
export { default as Process } from './Process'
export { Pricing } from './Pricing'
export { AddOns } from './AddOns'
export { Portfolio } from './Portfolio'
export { FAQ } from './FAQ'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'